# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import compute_pb2 as compute__pb2


class ComputeFiboStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Fibonacci = channel.unary_unary(
                '/ComputeFibo/Fibonacci',
                request_serializer=compute__pb2.Number.SerializeToString,
                response_deserializer=compute__pb2.Number.FromString,
                )


class ComputeFiboServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Fibonacci(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputeFiboServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Fibonacci': grpc.unary_unary_rpc_method_handler(
                    servicer.Fibonacci,
                    request_deserializer=compute__pb2.Number.FromString,
                    response_serializer=compute__pb2.Number.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ComputeFibo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ComputeFibo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Fibonacci(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ComputeFibo/Fibonacci',
            compute__pb2.Number.SerializeToString,
            compute__pb2.Number.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
