# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compute.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcompute.proto\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x05\x32.\n\x0b\x43omputeFibo\x12\x1f\n\tFibonacci\x12\x07.Number\x1a\x07.Number\"\x00\x42\x0f\n\x0b\x63om.ex.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compute_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.ex.grpcP\001'
  _globals['_NUMBER']._serialized_start=17
  _globals['_NUMBER']._serialized_end=40
  _globals['_COMPUTEFIBO']._serialized_start=42
  _globals['_COMPUTEFIBO']._serialized_end=88
# @@protoc_insertion_point(module_scope)
